In [1]:
using MLDatasets, Flux
train_data = MLDatasets.MNIST(split=:train)
test_data  = MLDatasets.MNIST(split=:test)

function loader(data; batchsize::Int=1)
    x1dim = reshape(data.features, 28 * 28, :) # reshape 28×28 pixels into a vector of pixels
    yhot  = Flux.onehotbatch(data.targets, 0:9) # make a 10×60000 OneHotMatrix
    Flux.DataLoader((x1dim, yhot); batchsize, shuffle=true)
end

loader (generic function with 1 method)

In [18]:
i=0
for (x,y) in loader(train_data, batchsize=3) 
    i+=1
end

length(train_data)

60000

In [16]:
i=0
for (x,y) in loader(train_data, batchsize=3) 
    println(size(x))
    break
end

length(train_data)

(784, 3)


60000

In [3]:
(x,y) = loader(train_data, batchsize=1) 
println(size(x[1]))
println(x[1])
println(x[2])

println(size(y[1]))
println(y[1])
println(y[2])

(784, 1)
Float32[0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0

In [4]:
include("graph_ops.jl")

net = declare_net(cross_entropy_loss,
RNN( 14*14 => 64, tanh),
# Dense( 14*14 => 64, tanh),
Dense( 64 => 10, nothing)
)

n_sequences=4

unfold_net!(net,n_sequences)

graph = net.graph
# pprint(graph)

new RNN: dims(Wx): (64, 196, " b: ", 64)
new Dense: dims(Wx): (10, 64, " b: ", 10)
init_node! OperationNode{typeof(mul!)}
input sizes: Tuple{Int64, Vararg{Int64}}[(64, 196), (196,)]
number of inputs: 2
init_node-successful! OperationNode{typeof(mul!)}
init_node! OperationNode{typeof(mul!)}
input sizes: Tuple{Int64, Vararg{Int64}}[(64, 196), (196,)]
number of inputs: 2
init_node-successful! OperationNode{typeof(mul!)}
init_node! OperationNode{typeof(mul!)}
input sizes: Tuple{Int64, Vararg{Int64}}[(64, 196), (196,)]
number of inputs: 2
init_node-successful! OperationNode{typeof(mul!)}
init_node! OperationNode{typeof(mul!)}
input sizes: Tuple{Int64, Vararg{Int64}}[(64, 196), (196,)]
number of inputs: 2
init_node-successful! OperationNode{typeof(mul!)}
init_node! OperationNode{typeof(mul!)}
input sizes: Tuple{Int64, Vararg{Int64}}[(64, 196), (196,)]
number of inputs: 2
init_node-successful! OperationNode{typeof(mul!)}
init_node! OperationNode{typeof(+)}
input sizes: [(64,), (64,)]
number o

37-element Vector{Node}:
 VariableNode([0.0036263084078527186 0.9143862741379741 … 0.882658376045889 0.518959683439557; 0.3316014222004019 0.868400282547394 … 0.9580758647255619 0.8571738626085459; … ; 0.3128750479829606 0.9306250954187453 … 0.5989536207475166 0.3897747982345007; 0.014940219813255107 0.5296605103285831 … 0.5100407127814166 0.03368335880593165], [0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], "Wx")
 VariableNode([0.5457506665497056 0.06564606084376667 … 0.9476856599435913 0.9283775654383353; 0.6577016750931916 0.9802195098322338 … 0.07541609760562917 0.7743795539663824; … ; 0.12304980870919247 0.987841183584652 … 0.8364564830537312 0.2187365161209721; 0.4623497294800051 0.4084152484746436 … 0.27319913461211287 0.9368382324798621], [0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], "Wxx")
 VariableNode([0.2930904059357622, 0.7381823121979003, 0.7534556574336723, 0.4498961387558216, 0.30831385633234054, 0.30

In [5]:
function loss_and_accuracy(net::Network, data)
    (x, y) = only(loader(data; batchsize=length(data)))
    reset!(net.graph)
    feed_with_sequence!(net,
        view(x, 1:196),
        view(x, 197:392),
        view(x, 393:588),
        view(x, 589:784))
    feed_desired_output!(net, y)
    forward!(net.graph)
    ŷ = net.output.output
    acc = round(100 * mean(Flux.onecold(ŷ) .== Flux.onecold(y)); digits=2)
    # Flux.reset!(model)
    # ŷ = model(x[  1:196,:])
    # ŷ = model(x[197:392,:])
    # ŷ = model(x[393:588,:])
    # ŷ = model(x[589:end,:])
    # loss = Flux.logitcrossentropy(ŷ, y)  # did not include softmax in the model
    # acc = round(100 * mean(Flux.onecold(ŷ) .== Flux.onecold(y)); digits=2)
    # (; loss, acc, split=data.split)  # return a NamedTuple
end

loss_and_accuracy (generic function with 1 method)

In [6]:
using Statistics: mean  # standard library

train_log = []
settings = (;
    eta = 15e-3,
    epochs = 5,
    batchsize = 100,
    lr = 0.05
)

(eta = 0.015, epochs = 5, batchsize = 100, lr = 0.05)

In [7]:
using ProgressMeter

loss_in_epoch = 0.0
losses = []


@time @inbounds for epoch in 1:settings.epochs
    loss_in_epoch = 0.0
    println("Epoch: ", epoch)
    reset!(graph)
    @time for (x, y) in loader(train_data, batchsize=settings.batchsize)
        feed_with_sequence!(net,
            # view(x, 1:196),
            # view(x, 197:392),
            # view(x, 393:588),
            # view(x, 589:784)
            x[1:196, :],
            x[197:392, :],
            x[393:588, :],
            x[589:784, :]
        )
        feed_desired_output!(net, y)
        currentloss = forward!(graph)
        backward!(graph)
        loss_in_epoch += first(currentloss)
    end
    adjust!(net.variables, settings.lr / length(train_data))
    println("Current loss: ", loss_in_epoch)
    push!(losses, first(loss_in_epoch))
    println("Accuracy: ", loss_and_accuracy(net, train_data))
end


Epoch: 1

DimensionMismatch: DimensionMismatch: cannot broadcast array to have fewer non-singleton dimensions

In [8]:
net.variables[1].output

10×64 Matrix{Float64}:
 0.00362631  0.914386  0.277168  0.476387   …  0.548847  0.882658  0.51896
 0.331601    0.8684    0.661848  0.244164      0.397143  0.958076  0.857174
 0.58232     0.396575  0.843798  0.26443       0.512409  0.780935  0.294056
 0.802998    0.833954  0.33564   0.064958      0.437059  0.987969  0.493958
 0.872289    0.264943  0.822689  0.0663174     0.372815  0.48396   0.944216
 0.0704003   0.410774  0.96886   0.0175537  …  0.32066   0.443886  0.900294
 0.129815    0.132196  0.96779   0.534796      0.163721  0.892266  0.830441
 0.200538    0.012674  0.950518  0.13905       0.363373  0.271365  0.155558
 0.312875    0.930625  0.680519  0.477761      0.599192  0.598954  0.389775
 0.0149402   0.529661  0.657017  0.549993      0.390305  0.510041  0.0336834

In [9]:
randn(10)

10-element Vector{Float64}:
  0.5581654960432754
 -1.039123219704783
 -1.444369223565446
 -0.8986112206263944
 -0.8751128503550246
  1.7308293164656867
 -0.18180991964167023
 -2.2028465874666043
  0.6810334272032942
  0.5147915530095982